#! /bin/sh

sxhkd &

## uncomment if you want to use them :)

#ws1=cli
#ws2=code
#ws3=browse
#ws4=media
#ws5=mail
#ws6=cli2
#ws7=edit
#ws8=steam
#ws9=browsebig
#ws0=code2


#bspc monitor eDP-1 -d $ws1 $ws2 $ws3 $ws4 $ws5
#bspc monitor DP-1 -d $ws6 $ws7 $ws8 $ws9 $ws0
bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

./.fehbg

bspc config border_width         8
bspc config window_gap          15

bspc config top_padding 15 
bspc config split_ratio          0.52
bspc config active_border_color '#929599'
bspc config normal_border_color '#23272E'
bspc config focused_border_color '#929599'
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


## Autostart

compton --config ~/compton.conf -b
#panel &

#polybar dracaether &
